apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-logging
  namespace: elastic-system
spec:
  version: 8.17.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
      action.auto_create_index: "true"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: longhorn