apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-init-script
  namespace: audit-demo
data:
  clickhouse-entrypoint.sh: |
    #!/bin/bash
    cat <<EOF > /etc/clickhouse-server/config.d/s3-minio.xml
    <yandex>
      <s3>
        <minio>
          <endpoint>http://minio-1720438607.minio.svc:9000</endpoint>
          <access_key_id>${S3_ACCESS_KEY_ID}</access_key_id>
          <secret_access_key>${S3_SECRET_ACCESS_KEY}</secret_access_key>
        </minio>
      </s3>
    </yandex>
    EOF

    exec /entrypoint.sh