apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: audit-demo
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        env:
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: access_key
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-credentials
                key: secret_key
        command: ["/bin/bash", "-c"]
        args:
          - |
            bash /etc/clickhouse-server/init/clickhouse-entrypoint.sh
        ports:
        - containerPort: 8123  # HTTP port
        - containerPort: 9000  # Native client port
        volumeMounts:
          - name: config-init
            mountPath: /etc/clickhouse-server/init/
            readOnly: true
          - name: clickhouse-storage
            mountPath: /var/lib/clickhouse
      volumes:
        - name: config-init
          configMap:
            name: clickhouse-init-script
            defaultMode: 0755
        - name: clickhouse-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: audit-demo
spec:
  selector:
    app: clickhouse
  ports:
    - port: 8123
      targetPort: 8123
      name: http
    - port: 9000
      targetPort: 9000
      name: native