apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-cache-pv
  namespace: tekton-executions
spec:
  storageClassName: standart
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/mnt/maven-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-pvc
  namespace: tekton-executions
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi