apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
  namespace: tekton-executions
spec:
  params:
  - name: repo
    type: string
    description: Repo URL
  - name: branch
    type: string
    description: Branch of the repo
    default: master
  - name: workspace
    type: string
    description: workspace
  - name: namespace
    type: string
    description: namespace
  - name: service
    type: string
    description: service
  - name: builder
    type: string
    description: builder image
  - name: version
    type: string
    description: version
  workspaces:
  - name: output
  steps:
  - name: build-maven-app
    image: $(params.builder)
    script: |
      #!/bin/sh
      cd $(workspaces.output.path)/$(params.workspace)/$(params.namespace)/$(params.service)/$(params.version)
      mvn clean package
      ls -ltrha ~/.m2/repository
      ls -lR
      if [ $? -ne 0 ]; then
        echo "Command failed. Changing Task status to failed."
        exit 1 # Explicitly set a non-zero exit code to fail the task
      fi
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2/repository
  volumes:
  - name: maven-cache
    persistentVolumeClaim:
      claimName: maven-cache-pvc