apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-build
  namespace: tekton-executions
spec:
  params:
  - name: repo
    type: string
    description: Repo URL
  - name: branch
    type: string
    description: Branch of the repo
    default: master
  - name: workspace
    type: string
    description: workspace
  - name: namespace
    type: string
    description: namespace
  - name: service
    type: string
    description: service
  - name: builder
    type: string
    description: builder image
  workspaces:
  - name: output
  steps:
  - name: build-node-app
    image: $(params.builder)
    script: |
      #!/bin/sh
      cd $(workspaces.output.path)/$(params.workspace)/$(params.namespace)/$(params.service)
      npm install
      ls -lR
      if [ $? -ne 0 ]; then
        echo "Command failed. Changing Task status to failed."
        exit 1 # Explicitly set a non-zero exit code to fail the task
      fi
    volumeMounts:
    - name: npm-cache
      mountPath: /root/.npm/_cacache
  volumes:
  - name: npm-cache
    persistentVolumeClaim:
      claimName: npm-cache-pvc