apiVersion: v1
kind: Secret
metadata:
  name: argo-api-credentials
  namespace: tekton-executions
data:
  test-argo-server: YXJnb2NkLmRldi50ci56aXAuY28=
  test-argo-username: YWRtaW4=
  test-argo-password: Zmk5YXdBb0UxOTc4ajZNYg==
  stg-argo-server: YXJnb2NkLnN0Zy50ci56aXAuY28=
  stg-argo-username: YWRtaW4=
  stg-argo-password: NzhNTjBYNGtlQUxuaVU0Nw==
  prod-argo-server: YXJnb2NkLnRyLnppcC5jbw==
  prod-argo-username: YWRtaW4=
  prod-argo-password: aE03MDBfSlxidGlwdFc1
