apiVersion: v1
kind: Namespace
metadata:
  name: audit-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-app
  namespace: audit-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-app
  template:
    metadata:
      labels:
        app: audit-app
    spec:
      containers:
        - name: app
          image: registry.tr.zip.co/audit-flask-app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: audit-demo
stringData:
  access_key: minio
  secret_key: minio123
---
apiVersion: v1
kind: Service
metadata:
  name: audit-flask-app
  namespace: audit-demo
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: audit-app
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
