apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-clean-workspace-with-kubectl-sa-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tekton-executions
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io