apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-logging
spec:
  replicas: 3
  roles:
    - controller
  resources:
    requests:
      memory: 1Gi
      cpu: "0.1"
    limits:
      memory: 4Gi
      cpu: "1"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
        class: longhorn
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-logging
spec:
  replicas: 3
  roles:
    - broker
  resources:
    requests:
      memory: 1Gi
      cpu: "0.1"
    limits:
      memory: 4Gi
      cpu: "1"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
        class: longhorn
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-logging
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
#    image: my-org/my-image:latest
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.retention.ms: 1680000 # 28 min
      log.cleanup.policy: "delete"
      log.retention.check.interval.ms: 300000
      log.cleaner.backoff.ms: 15000
      log.cleaner.delete.retention.ms: 86400000
      log.segment.delete.delay.ms: 60000
      log.flush.scheduler.interval.ms: 2000
      log.flush.interval.ms: 50000
      log.flush.interval.messages: 100000
      log.cleaner.threads: 8
  entityOperator:
    topicOperator: {}
    userOperator: {}