apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: python-ci-pipeline
  namespace: tekton-executions
spec:
  params:
  - name: repo
    type: string
    description: Repo URL
    default: git@github.com:erkanderon/tekton-python.git
  - name: branch
    type: string
    description: Branch of the repo
    default: master
  - name: workspace
    type: string
    description: Workspace
    default: flower
  - name: namespace
    type: string
    description: Namespace
    default: authentication
  - name: service
    type: string
    description: Service
    default: tekton-python
  - name: registry
    type: string
    description: Registry Address
    default: registry.minikube.local:5000
  - name: version
    type: string
    description: Image Version
    default: latest
  workspaces:
    - name: codebase
  tasks:
    - name: clone
      params:
        - name: repo
          value: $(params.repo)
        - name: branch
          value: $(params.branch)
        - name: workspace
          value: $(params.workspace)
        - name: namespace
          value: $(params.namespace)
        - name: service
          value: $(params.service)
      taskRef:
        name: clone
      workspaces:
        - name: output
          workspace: codebase
    - name: docker-build-push
      params:
        - name: image
          value: $(params.registry)/$(params.workspace)/$(params.namespace)/$(params.service):$(params.version)
        - name: workspace
          value: $(params.workspace)
        - name: namespace
          value: $(params.namespace)
        - name: service
          value: $(params.service)
      taskRef:
        name: docker-build-push
      workspaces:
        - name: output
          workspace: codebase
      runAfter:
        - clone
  finally:
    - name: clean-workspace
      params:
        - name: workspace
          value: $(params.workspace)
        - name: namespace
          value: $(params.namespace)
        - name: service
          value: $(params.service)
      taskRef: 
        name: clean-workspace
      workspaces:
        - name: output
          workspace: codebase
#    - name: cleanup-task
#      params:
#        - name: namespace
#          value: tekton-executions
#      taskRef: 
#        name: clean-completed-tasks