apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-finished-pod
  namespace: tekton-executions
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: tekton-trigger
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl create -f - <<EOF
                  apiVersion: tekton.dev/v1
                  kind: TaskRun
                  metadata:
                    generateName: clean-completed-tasks-
                    namespace: tekton-executions
                  spec:
                    taskRef:
                      name: clean-completed-tasks
                    params:
                      - name: namespace
                        value: tekton-executions
                  EOF
          restartPolicy: OnFailure