apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build-push
  namespace: tekton-executions
spec:
  workspaces:
  - name: output
    description: The workspace containing the Dockerfile and build context.
  params:
  - name: image
    type: string
    description: The name of the image to build and push.
  - name: workspace
    type: string
    description: workspace
  - name: project
    type: string
    description: project
  - name: service
    type: string
    description: service
  - name: version
    type: string
    description: version
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=$(workspaces.output.path)/$(params.workspace)/$(params.project)/$(params.service)/$(params.version)/Dockerfile"
    - "--context=$(workspaces.output.path)/$(params.workspace)/$(params.project)/$(params.service)/$(params.version)"
    - "--destination=$(params.image)"
    - "--insecure"
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: registry-credentials