apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-build
  namespace: tekton-executions
spec:
  params:
  - name: repo
    type: string
    description: Repo URL
  - name: branch
    type: string
    description: Branch of the repo
    default: master
  - name: workspace
    type: string
    description: workspace
  - name: project
    type: string
    description: project
  - name: service
    type: string
    description: service
  - name: builder
    type: string
    description: builder image
  - name: version
    type: string
    description: version
  workspaces:
  - name: output
  steps:
  - name: build-go-app
    image: $(params.builder)
    script: |
      #!/bin/sh
      cd $(workspaces.output.path)/$(params.workspace)/$(params.project)/$(params.service)/$(params.version)
      if [ ! -f go.mod ]; then
        go mod init application
        go mod download
        go build -o app
      else
        go mod download
        go build -o app
      fi
      if [ $? -ne 0 ]; then
        echo "Command failed. Changing Task status to failed."
        exit 1 # Explicitly set a non-zero exit code to fail the task
      fi
    volumeMounts:
    - name: go-cache
      mountPath: /root/.cache/go-build
  volumes:
  - name: go-cache
    persistentVolumeClaim:
      claimName: go-cache-pvc