apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: tekton-executions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-role
  namespace: tekton-executions
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineruns/finalizers", "pipelines", "taskruns", "tasks"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-rolebinding
  namespace: tekton-executions
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
roleRef:
  kind: Role
  name: tekton-triggers-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-interceptor-viewer # Yeni bir ClusterRole adı verdim
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["*"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-interceptor-binding # Yeni bir ClusterRoleBinding adı verdim
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: tekton-executions # ServiceAccount'ınızın bulunduğu namespace'i buraya yazın
roleRef:
  kind: ClusterRole
  name: tekton-triggers-interceptor-viewer # Yukarıda oluşturduğumuz ClusterRole'un adı
  apiGroup: rbac.authorization.k8s.io