apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: audit-demo
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*audit-app*.log
      pos_file /var/log/fluentd.pos
      tag kube.audit
      read_from_head true
      <parse>
        @type regexp
        expression /^(?<time>[^ ]+)\s+stderr\s+\w\s+(?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    <filter kube.audit>
      @type parser
      key_name log
      <parse>
        @type json
      </parse>
    </filter>

    <match kube.audit>
      @type s3

      s3_bucket audit-logs
      s3_region us-east-1
      s3_endpoint http://minio-1720438607.minio.svc:9000

      aws_key_id "#{ENV['S3_ACCESS_KEY_ID']}"
      aws_sec_key "#{ENV['S3_SECRET_ACCESS_KEY']}"

      path logs/audit/%Y/%m/%d/
      buffer_path /fluentd/buffer/s3

      s3_object_key_format %{path}%{time_slice}_%{index}.log.gz
      time_slice_format %H%M
      time_slice_wait 10s
      store_as gzip

      force_path_style true
      utc true
      auto_create_bucket true
    </match>