apiVersion: v1
kind: ConfigMap
metadata:
  name: templates
  namespace: tekton-executions
data:
  deployment.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: $(name)
      name: $(name)
      namespace: $(namespace)
    spec:
      replicas: $(replicas)
      selector:
        matchLabels:
          app: $(name)
      template:
        metadata:
          labels:
            app: $(name)
        spec:
          containers:
          - env:
            - name: ENVIRONMENT
              value: $(environment)
            image: $(image)
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
            name: $(name)
            ports:
            - containerPort: 8080
              name: tcp-8080
              protocol: TCP
            - containerPort: 8081
              name: tcp-8081
              protocol: TCP
            readinessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
            resources:
              limits:
                cpu: 200m
                memory: 1024Mi
              requests:
                cpu: 200m
                memory: 1024Mi
  service.yaml: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: $(name)
      namespace: $(namespace)
      labels:
        apps: $(name)
    spec:
      type: ClusterIP
      ports:
      - port: 8080
        targetPort: 8080
        name: tcp-8080
      - port: 8081
        targetPort: 8081
        name: tcp-8081
      selector:
        app: $(name)
