apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: audit-demo
data:
  access_key: ZkltOENsRXdDb1BQQnhvaFB4WHE=
  secret_key: MHowOG9Vc1NEVTZuSUt6Y3lYejd6azA0VjhuWHhOSGFGQ0F5MHNVUg==
type: Opaque
